ye    # def save(self, commit=True):
    #     instance: UserAvatar = super().save(commit=False)
    #     instance.u_id = get_user_model().id
    #     instance.save()
    #     return instances
we will use flask not django
YES    # def save(self, commit=True):
    #     instance: UserAvatar = super().save(commit=False)
    #     instance.u_id = get_user_model().id
    #     instance.save()
    #     return instance
    
    
    
        # def save(self, commit=True):
    #     instance: UserAvatar = super().save(commit=False)
    #     instance.u_id = get_user_model().id
    #     instance.save()
    #     return instance
